[ci] Update destination dir on s3
kuzzleio/sdk-c pull request #18
Opened 2018-10-17 23:22 UTC by alexandrebouthinon

## What does this PR do ?
Update destination dir on s3

### How should this be manually tested?
You cannot :/ 

### Other changes
Wait 10 sec to be sure all lambda execution have been completed.

2018-10-18 11:33 UTC, benoitvidis approved these changes

2018-10-23 11:03 UTC, scottinet commented on .travis.yml
> +  - sleep 10 && aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
What's this sleep for?
Also, this PR's description states that it removes cloudfront invalidation, but that doesn't seem to be the case

2018-10-23 12:03 UTC, jenow requested changes

2018-10-23 12:03 UTC, jenow commented on .travis.yml
> +  - sleep 10 && aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
why a sleep here ?

2018-10-24 15:20 UTC, alexandrebouthinon commented
Useless now

2018-10-24 15:20 UTC, closed without merging