Add default room options
kuzzleio/sdk-c pull request #20
Opened 2018-10-24 09:40 UTC by Aschen

## What does this PR do ?

When writing the `relatime:subscribe` documentation for CPP and Java I thought I found a bug because I didn't receive notification when I pass a `room_options` with `scope = "out"`.  
After 2h I finally found why, it was just because when I create a new `room_options` struct, the `subscribe_to_self` option is set to false :upside_down_face: 

This PR add a macro to initialize the `room_options` struct with default values.

### How should this be manually tested?

  - Step 1 : Run a kuzzle stack and create the index `nyc-open-data` and the collection `yellow-taxi`
  - Step 2 : Download this snippet: https://gist.github.com/Aschen/3028d28e5592386fe0cd36a110977b6c
  - Step 3 :  Compile the CPP SDK: `docker run --rm -it --network ci_default --link kuzzle -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc make clean all`
 - Step 4 : Copy `kuzzlesdk.h`: `cp sdk-c/include/kuzzlesdk.h include/.`
 - Step 5 : Compile and run the snippet `g++ -std=c++11 realtimesubscribe-documents-leave-scope.cpp -Iinclude -L./build/ -lkuzzlesdk -lpthread -o documentnotification && LD_LIBRARY_PATH=./build ./documentnotification`

### Other changes

 - rename `room_options.user` to `room_options.users` to match the API

### Boyscout

2018-10-24 12:50 UTC, scottinet requested changes

2018-10-24 12:50 UTC, scottinet commented on cgo/kuzzle/destructors.go
> +		if st.volatiles != nil {
useless test: `free(NULL)` is a documented behavior, resulting in a no-op

2018-10-24 15:26 UTC, scottinet approved these changes

2018-10-25 08:17 UTC, etrousset approved these changes

2018-10-25 08:18 UTC, merged