Wrap the protocol
kuzzleio/sdk-c pull request #29
Opened 2018-11-12 13:28 UTC by jenow

## What does this PR do ?

Kuzzle now takes the protocol (which is a struct with pointer function) as parameter.

https://github.com/kuzzleio/sdk-cpp/pull/22/ :arrow_right:

2018-11-12 13:56 UTC, alexandrebouthinon approved these changes
Nice job ! :+1: :taco:

2018-11-13 09:45 UTC, etrousset requested changes
Nice job man :+1:

2018-11-13 09:45 UTC, etrousset commented on README.md
> +You should now have the SDK in the build directory.
Duplicated line

2018-11-15 14:02 UTC, etrousset approved these changes

2018-11-15 14:03 UTC, merged