Add badge for build and link to S3 to README.md
kuzzleio/sdk-c pull request #7
Opened 2018-09-27 09:00 UTC by jenow

## What does this PR do ?

Added the build badge and the links to download tgz archive.

2018-09-27 12:32 UTC, scottinet requested changes

2018-09-27 12:32 UTC, scottinet commented on README.md
>  The C SDK implement the websocket protocol.
implements

2018-09-27 12:32 UTC, scottinet commented on README.md
> +cd sdk-go
cd sdk-c

2018-09-27 12:32 UTC, scottinet commented on README.md
>  ### Clone the depot
See my comment in the Java SDK PR

2018-09-27 12:32 UTC, scottinet commented on README.md
>  You should know have the SDK in the build directory.
You should now

2018-09-27 12:32 UTC, scottinet commented on README.md
> +i386:  https://dl.kuzzle.io/sdk/c/master/kuzzlesdk-cpp-i386-1.0.0.tar.gz
i386 => x86

2018-09-27 14:01 UTC, Aschen approved these changes

2018-09-27 14:18 UTC, benoitvidis reviewed
I am a little concerned that we're going to miss the dl urls updates.
Shouldn't we wait to have a `xxx/latest/xxx` url before including the links?

2018-10-01 07:54 UTC, jenow commented
@benoitvidis I agree but this does not exist on our s3

2018-10-02 08:21 UTC, scottinet approved these changes

2018-10-02 08:34 UTC, merged